on: [push]

jobs:
  build_push_docker_image:
    runs-on: ubuntu-latest
    name: Build and push Docker image
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: thierrysans/microblog
        tags: latest
    - name: execute playbook
      uses: dawidd6/action-ansible-playbook@v2
      with: 
        playbook: myplaybook.yml
        inventory: |
          cms-weblab.utsc.utoronto.ca ansible_connection=ssh ansible_user=gaochen8 ansible_ssh_pass=${{secrets.SSH_KEY}} 
        options: |
          --tags "recreate-hello"
